gefor_platform_formation:
    resource: "@GEFORPlatformBundle/Controller/FormationController.php"
    type:     annotation

gefor_platform_situation:
    resource: "@GEFORPlatformBundle/Controller/SituationController.php"
    type:     annotation

gefor_platform:
    resource: "@GEFORPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: GEFORUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

   