security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        GEFOR\UserBundle\Entity\User: plaintext



    role_hierarchy:
        ROLE_USER:        [ROLE_VISITEUR] #a le droit de consulter les tables
        ROLE_ADMIN:       [ROLE_VISITEUR, ROLE_DEVELOPPEUR] #a le droit de consulter, modifier et creer des tables
        ROLE_SUPER_ADMIN: [ROLE_VISITEUR,ROLE_DEVELOPPEUR, ROLE_ADMINISTRATEUR] #a le droit de consulter, supprimer et creer des tables

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:  GEFOR\UserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:   main
            form_login:
                login_path: login
                default_target_path: Inscription
                check_path: login_check
            logout:
                path:       logout
                target:     login

    
    access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    

        