Inscription_show:
    path:     /platform/show/{id}
    defaults: { _controller: GEFORPlatformBundle:Inscription:show }

Admin:
    path:     /platform/admin
    defaults: { _controller: GEFORPlatformBundle:Inscription:admin }

Admin_stats:
    path:     /platform/admin/stats
    defaults: { _controller: GEFORPlatformBundle:Inscription:stats }


gefor_platform_homepage:
    path:     /
    defaults: { _controller: GEFORPlatformBundle:Default:index }




Inscription:
    path:     /platform
    defaults: { _controller: GEFORPlatformBundle:Inscription:index }

Inscription_new:
    path:     /platform/{id}
    defaults: { _controller: GEFORPlatformBundle:Inscription:new }


Inscription_delete:
    path:     /platform/delete/{id}
    defaults: { _controller: GEFORPlatformBundle:Inscription:delete }

Inscription_edit:
    path:     /platform/edit/{id}
    defaults: { _controller: GEFORPlatformBundle:Inscription:edit }


